# Configuración básica del sitio
baseurl: ''
url: 'https://ivlumedicinaestetica.com'
name: Ivonne Vanessa Camacho Viancha
title: "Centro medico IVLU en Bogotá | Dra.Luisa & Dra.Ivonne"
description: "Rejuvenecimiento facial y restauración capilar en Bogotá. Transforma tu imagen con tecnología de vanguardia y médicos especialistas certificados."
email: Ipsivlumedicinaestetica@gmail.com
maps: https://g.co/kgs/Eg89pm4
direccion: "Calle 127 A #7-19 Consultorio 513, Usaquén, Bogotá"
telefono: 3228351465
instagram: https://www.instagram.com/ivluoficial/
facebook: https://www.facebook.com/ivluoficial/
tiktok: https://www.tiktok.com/@ivluoficial

# Información del autor y social
author:
  name: Ivonne Vanessa Camacho Viancha
  email: ipsivlumedicinaestetica@gmail.com
  instagram: https://www.instagram.com
  facebook: https://www.facebook.com
  youtube: https://www.youtube.com/
  job_title: "Especialista en medicina estética y láser"
  bio: "La Dra. es una destacada especialista en Medicina Estética..."

# SEO Configuration
tagline: "Especialista en medicina estética: Enfoque médico, resultados naturales"
logo: /assets/images/logo.png
social:
  name: Dra.Luisa & Dra.Ivonne | Expertas en rejuvenecimiento
  links:
    - https://www.instagram.com/
    - https://www.facebook.com/
    - https://www.youtube.com/

# Publisher
publisher:
  name: Ivonne Vanessa Camacho Viancha
  logo: /assets/images/logo.png

markdown: kramdown

# Configuración de URLs y colecciones
permalink: /:categories/:title/

default_lang: "es"

collections:
  redirects:
      output: true
  servicios_es:
    output: true
    permalink: /es/servicios/:title/
  servicios_en:
    output: true
    permalink: /en/services/:title/
  tecnologia_es:
    output: true
    permalink: /es/tecnologias/:title/
  tecnologia_en:
    output: true
    permalink: /en/technologies/:title/

# Valores por defecto
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "_posts/es"
    values:
      lang: "es"
      permalink: /es/blog/:title/
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      permalink: /en/blog/:title/
  - scope:
      path: ""
      type: "servicios_es"
    values:
      layout: "servicios"
  - scope:
      path: ""
      type: "servicios_en"
    values:
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_es"
    values:
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_en"
    values:
      layout: "servicios"
 
keep_files: [/img]

# Optimización HTML
compress_html:
  endings: ["li", "dt", "dd", "optgroup", "option", "colgroup", "caption", "thead", "tbody", "tfoot", "tr", "td", "th"]
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
